### PR TITLE
Expose encode/decode methods for external extension.

### PR DESCRIPTION
**Pull request by mosquito**
Hi, I guess this will be useful in case e.g. pickle index.

```python
import pickle
from sophy import BytesIndex

class PickleIndex(BytesIndex):
    def encode(self, obj):
        return pickle.dumps(obj)

    def decode(self, value):
        return pickle.loads(value)
```

### CODE REVIEW

**Comment by coleifer** [comment]
I think I'm going to pass on these changes, but will leave it open for now. I'd propose implementing pickling at a higher-level using a `BytesIndex`, which would correctly handle storage and retrieval.

**Comment by mosquito** [comment]
It’s not only for pickling. With this interface extension I plan to make the UUID key and MsgPack in my project.

**Comment by coleifer** [comment]
I think I'd prefer to implement this as a subclass of BytesIndex that accepts serialization callables for serializing and deserializing data. Then it'd b trivial to implement msgpack, uuid, pickle, etc.

**Comment by coleifer** [comment]
Very nice, you mind if I pick a few tidbits to merge into my repo?

**Comment by coleifer** [comment]
You might be interested in this commit, which adds a `SerializedIndex`: 0073b2805dd8bb51dba9ed52e29bab69026227b6

You'd use it:

```python
schema = Schema([StringIndex('key')], [SerializedIndex('value', pickle.dumps, pickle.loads)])
```

**Comment by coleifer** [comment]
@mosquito - fyi, I've added support for:

* JsonIndex
* MsgPackIndex
* PickleIndex
* UUIDIndex
* SerializedIndex (arbitrary serialize/deserialize)

**Pull request closed without merging**
